name: RegionCommand
version: 1.0
main: net.snailz.regioncommand.RegionCommand
depend: [WorldEdit]
author: Snailz
commands:
    rgc:
        permission: portalcommand.command
        description: The main command for PortalCommand
        usage: Syntax error! do /rgc help for information on how to use PortalCommand commands!
        
permissions:
    regioncommand.*:
        description: Gives access to all portalcommand features
        children:
            portalcommand.command: true
            portalcommand.use: true
    regioncommand.use:
        description: Allow PortalCommand to run a command when you enter a region
        default: true
    regioncommand.command:
        description: Gives a player permission to edit PortalCommand regions
        default: op